### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by JerzyKruszewski** [JerzyKruszewski/BajarzRPG#1]
## Version 1.0.0
- [ ] Character Creation
- [ ] Races
- [ ] Classes
- [ ] Basic stats (Strength, Dexterity, Intelligence, Charisma)
- [ ] Basic inventory (Weapon, Armor)
- [ ] Basic turn based combat system for 2 characters
- [ ] Loot system

## Future plans
- [ ] Little more advanced combat system with multiple characters
- [ ] NPCs
- [ ] Followers
- [ ] Familiars
- [ ] Consumables
- [ ] Shops
- [ ] Multi language support
- [ ] Quests
- [ ] Storyline
